#! /bin/bash

yum install xfsprogs -y

mkdir /home/ec2-user/disk2
mkdir /home/ec2-user/disk3

mkfs -t xfs /dev/nvme1n1
mkfs -t xfs /dev/nvme2n1

echo $(blkid | grep /dev/nvme1n1 | awk '{print $2}') /home/ec2-user/disk2 xfs defaults 1 1 >> /etc/fstab
echo $(blkid | grep /dev/nvme2n1 | awk '{print $2}') /home/ec2-user/disk3 xfs defaults 1 1 >> /etc/fstab

mount -a

